name: NHL Data Pipeline

on:
  push:
    branches: [ main, master ]
    paths:
      - 'scripts/**'
      - 'data/nhl/**'
      - 'requirements.txt'
      - '.github/workflows/nhl-pipeline.yml'
  workflow_dispatch: {}   # allow manual run

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NHL processing
        run: |
          python scripts/process_nhl.py

      - name: Upload outputs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nhl-outputs
          path: outputs/
          if-no-files-found: warn
